### ISSUE TITLE
new logo/icon

### ISSUE THREAD

**Issue by mansya** [MD-AZMAL/Sharp-Tune#3]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by MD-AZMAL** [comment]
hey thanks for such positive response... i was busy with my other project so I wasn't able to. reply

**Comment by MD-AZMAL** [comment]
your contribution are always welcomed

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you like it ?

![sharp tune](https://user-images.githubusercontent.com/33461607/43476358-9b98ace6-9522-11e8-8f63-35d736c559df.png)

sorry for a long time

**Comment by MD-AZMAL** [comment]
@mansya these are awesome, nice work dude! i would suggest adding something that is related to color scheme of the player..... and see if making the edges of triangle rounded ... i think it would look...
try them when you are free i am not forcing :P

**Comment by mansya** [comment]
what do you think about this ? 
![sharp tune](https://user-images.githubusercontent.com/33461607/43576698-252ca370-9674-11e8-8761-56862a6e675f.png)

**Comment by mansya** [comment]
If you want to change the color you can give me the code color RGB

**Comment by MD-AZMAL** [comment]
i will do so.... just give me some time little pre occupied

**Comment by mansya** [comment]
I will wait for you to give instructions to me to do pull requests.

**Comment by MD-AZMAL** [comment]
cool

**Comment by MD-AZMAL** [comment]
#EBEBEB
#9D9D9D
#DC0A2A
#AA021B
#262626

this is the color scheme

**Comment by mansya** [comment]
do you mean like this ? if yes. which one do you like?
![variation](https://user-images.githubusercontent.com/33461607/43990063-335b319c-9d80-11e8-9d62-8d5efe14192a.png)

**Comment by MD-AZMAL** [comment]
5th one is good ......... i have some designs in my mind too i will upload it soon and then we can see what path we can take......... Thanks for the effort

**Comment by mansya** [comment]
Yes. I'll wait for it. in this project or in another project sir?

**Comment by MD-AZMAL** [comment]
lol don't call me sir 😄 .... for this project only i will get to you

**Comment by MD-AZMAL** [comment]
![logo](https://user-images.githubusercontent.com/33421347/44042228-5dd74a1e-9f3d-11e8-8924-254c21d3ccbf.png)

how about this?

**Comment by mansya** [comment]
That is cool. do you design it?

**Comment by mansya** [comment]
I've make lots of color variations. No 1 is the color of the logo that you give to me. How ? which one will you choose?
![variation](https://user-images.githubusercontent.com/33461607/44156787-fcca1734-a0da-11e8-97de-f8b7246d0d3e.png)

**Comment by mansya** [comment]
I've make lots of color variations. No 1 is the color of the logo that you give to me. How ? which one will you choose?
![variation](https://user-images.githubusercontent.com/33461607/44156787-fcca1734-a0da-11e8-97de-f8b7246d0d3e.png)

**Comment by MD-AZMAL** [comment]
Good work ... can you do just a small modification then we can finalize which color .... replace that music symbol with # ... this is the last change then we can think of the color

**Comment by mansya** [comment]
yes which one should be modified?

**Comment by MD-AZMAL** [comment]
in all. of them... then it would be easy to visualize

**Comment by mansya** [comment]
Do you mean like this ?
![variation1](https://user-images.githubusercontent.com/33461607/44188944-a6a0ad80-a14a-11e8-86eb-f5c0e4278108.png)

**Comment by MD-AZMAL** [comment]
yes... like this we will go with 6...and make the # a bit bold... and decrease no of lines on the left.. keep only 5 lines

**Comment by mansya** [comment]
do you mean like this ? if yes tell me. I'll make pull requests.
![master](https://user-images.githubusercontent.com/33461607/44242673-14a1af00-a1f5-11e8-9560-67e84fd80c2c.png)

**Comment by MD-AZMAL** [comment]
nice... give a pull request

**Comment by MD-AZMAL** [comment]
give me the psd or ai file.......make it rar file and send it

**Comment by mansya** [comment]
ok. I'll make pull requests now. And I will sent you all files.

**Comment by mansya** [comment]
I have upload all files to this link
https://drive.google.com/open?id=1l0L3b43oSybaop790YJQwnXN-8shsNyR

And I have sent [pull requests](https://github.com/MD-AZMAL/Sharp-Tune/pull/5). please check it.

**Comment by MD-AZMAL** [comment]
i will check asap

**Comment by mansya** [comment]
ok

**Comment by MD-AZMAL** [comment]
Thanks for the logo 😄
